### ISSUE TITLE
Errors from affixes2analysis.py during building

### ISSUE THREAD

**Issue by Traubert** [koskenni/ofitwol#1]
In 934fcf88d05dbdb3dce28615d7ad41c80a2341b2, when I run `make` in ofitwol/, I run into:

`python3 affies2analysis.py: error: unrecognized arguments: -e`

affies2analysis is a typo in the code, but I'm not sure what the -e option is for. If I remove it from the Makefile, I get:

```$ make
python3 affixes2analysis.py ofi-affixes.csv analy-aff.lexc
Traceback (most recent call last):
  File "affixes2analysis.py", line 84, in <module>
    if r["MODE"] and not args.mode in r["MODE"]:
KeyError: 'MODE'
Makefile:117: recipe for target 'analy-aff.lexc' failed
make: *** [analy-aff.lexc] Error 1
```

If I add the test `"MODE" in r` to the erroring line, the next error is from a missing Makefile target, which I will mention in another issue.

**Comment by koskenni** [comment]
Sorry, the READMEs were not up to date. Now they are updated. In essence, use the files and the Makefile in the ofitwol/ofi2 subdirectory, not in the ofitwol directory.
